version: '3.4'

volumes:
  bundler_cache: {}
  database: {}
  application: {}
  asset_cache: {}

networks:
  backend: {}
  frontend: {}

services:
  #db:
  # image: postgres:9.5
  # nginx:
    # build:
    #   context: .
    #   dockerfile: ./config/deploy/nginx/Dockerfile
    # networks: [ "backend", "frontend" ]
    # depends_on:
    #   - app
    # ports:
    #   - '3737:80'
    #   - '3738:443'
  app:
    image: rekrei/rekrei:master
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/rekrei
      - asset_cache:/rekrei/public
    ports:
      - "3037:3000"
    env_file: .env
    environment:
      #DATABASE_URL: "postgres://postgres@db:5432/rekrei_development?pool=5"
      RAILS_ENV: production
      RACK_ENV: production
