FROM rekrei/rekrei-base:2.3.1

MAINTAINER Matthew Vincent <matt@averails.com>

RUN mkdir /rekrei
WORKDIR /rekrei
COPY Gemfile /rekrei/Gemfile
COPY Gemfile.lock /rekrei/Gemfile.lock
RUN gem install bundler && bundle install --jobs 20 --retry 5
RUN bundle exec rake db:create
COPY . /rekrei
