Rails.application.config.assets.version = '1.0'
Rails.application.config.assets.precompile += %w( progressbar.gif )
Rails.application.config.assets.precompile += %w( loading.gif )
Rails.application.config.assets.precompile += %w( page-background.png )
Rails.application.config.assets.precompile += %w( stay-connected.png )
Rails.application.config.assets.precompile += %w( images.js )
Rails.application.config.assets.precompile += %w( html5shiv.js )
Rails.application.config.assets.precompile += %w( respond.min.js )
Rails.application.config.assets.precompile += %w( rekrei.icns )
